#ifndef CAMPP_PROFILL_QCONV_V5_STAGE_TAGS_H
#define CAMPP_PROFILL_QCONV_V5_STAGE_TAGS_H

typedef enum CamppQconvV5StageTag {
    CAMPP_QCONV_V5_STAGE_VALIDATED_RAW = 0,
    CAMPP_QCONV_V5_STAGE_ZERO_POINT_FASTPATH = 1,
    CAMPP_QCONV_V5_STAGE_WEIGHT_PACK = 2,
    CAMPP_QCONV_V5_STAGE_REAL_8X8_MAC = 3,
    CAMPP_QCONV_V5_STAGE_3X3_UNROLL = 4,
    CAMPP_QCONV_V5_STAGE_3X3_SLIDING = 5,
    CAMPP_QCONV_V5_STAGE_ADDRESS_PLAN = 6,
    CAMPP_QCONV_V5_STAGE_ADDRESS_1X1 = 7,
    CAMPP_QCONV_V5_STAGE_ADDRESS_3X3 = 8,
    CAMPP_QCONV_V5_STAGE_ADDRESS_GENERIC = 9
} CamppQconvV5StageTag;

const char *campp_qconv_v5_stage_tag_name(CamppQconvV5StageTag tag);

#endif /* CAMPP_PROFILL_QCONV_V5_STAGE_TAGS_H */
