#ifndef CAMPP_PROFILL_QCONV_MAC_V5_COMMON_H
#define CAMPP_PROFILL_QCONV_MAC_V5_COMMON_H

#include "qconv_mac_4x8.h"
#include "qconv_v4_tile_plan.h"

#define CAMPP_QCONV_V5_OUTPUT_TILE CAMPP_QCONV_CANDIDATE_OUTPUT_TILE
#define CAMPP_QCONV_V5_SPATIAL_TILE CAMPP_QCONV_CANDIDATE_TILE

#endif /* CAMPP_PROFILL_QCONV_MAC_V5_COMMON_H */
